# Generated by Django 4.2.16 on 2026-06-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vigilante', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='registromanual',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'managed': False},
        ),
    ]
