"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.
"""

# ==================== CONFIGURACIÓN INICIAL ====================
import sys
import os
from dotenv import load_dotenv, dotenv_values
load_dotenv()
env_vars = dotenv_values(os.path.join(os.path.dirname(__file__), '..', '.env'))

# La importación de pymysql es opcional en entornos sin la dependencia instalada.
try:
    import pymysql
    pymysql.version_info = (2, 2, 1, "final", 0)
    pymysql.install_as_MySQLdb()
except Exception:
    # Si no está disponible, seguimos sin bloquear el inicio; la conexión a BD
    # fallará en tiempo de ejecución si se requiere MySQL y la librería no está.
    pymysql = None
STATIC_URL = 'static/'
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]
pymysql.version_info = (2, 2, 1, "final", 0)
pymysql.install_as_MySQLdb()
from pathlib import Path

# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== SEGURIDAD ====================
SECRET_KEY = 'django-insecure-%u1ia%ra2e#7@s9o4cf#go!xzs5!=38k7!5!(8+ysvpy7u(o41'
DEBUG = True
ALLOWED_HOSTS = ['securesab.app', 'www.securesab.app', '158.23.17.242', 'localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    'https://securesab.app',
    'https://www.securesab.app',
    'http://securesab.app',
    'http://www.securesab.app',
]

# ==================== APLICACIONES ====================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Nuestras apps (organizadas por módulos)
    'apps.login',
    'apps.gestion_asistencia_justificacion.aprendiz.apps.AprendizConfig',
    'apps.gestion_asistencia_justificacion.instructor',
    'apps.reporte_monitoreo.coordinador',
    'apps.seguridad_administracion.vigilante',
    'apps.gestor_sistema',
    
    
]

# ==================== MIDDLEWARE ====================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ==================== TEMPLATES ====================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'apps',  # ← PARA QUE ENCUENTRE base.html EN apps/
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'config.wsgi.application'

# ==================== BASE DE DATOS ====================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'secure11',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

DATABASES['default']['USER'] = env_vars.get('DATABASE_USER', '') or 'root'
DATABASES['default']['PASSWORD'] = env_vars.get('DATABASE_PASSWORD', '') or ''

if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }


# ==================== VALIDACIÓN DE CONTRASEÑAS ====================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==================== HASHERS DE CONTRASEÑAS ====================
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

# ==================== INTERNACIONALIZACIÓN ====================
LANGUAGE_CODE = 'es-co'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# ==================== CONFIGURACIÓN DE AUTENTICACIÓN ====================
LOGIN_URL = 'login:login'
LOGIN_REDIRECT_URL = 'login:mi_perfil'
LOGOUT_REDIRECT_URL = 'login:login'

# Modelo personalizado de usuarios
AUTH_USER_MODEL = 'login.Usuarios' 

# ==================== ARCHIVOS ESTÁTICOS (CSS, JS, IMÁGENES) ====================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# NOTA: Los archivos estáticos van en cada app, en su carpeta static/
# No necesitamos STATICFILES_DIRS porque cada app tiene su propia carpeta static
# Esto le dice a Django que busque en la carpeta 'static' de cada app registrada
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]

STATICFILES_DIRS = [
    BASE_DIR / 'apps' / 'static',
]

# ==================== ARCHIVOS MEDIA (ARCHIVOS SUBIDOS POR USUARIOS) ====================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =====================================================
# CONFIGURACIÓN DE CORREO ELECTRÓNICO
# =====================================================

# Configuración de correo:
# - Usa SMTP por defecto para enviar correos reales.
# - La clave puede llegar por GMAIL_APP_PASSWORD o EMAIL_HOST_PASSWORD.

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'securesabsena@gmail.com'
EMAIL_HOST_PASSWORD = env_vars.get('GMAIL_APP_PASSWORD', '') or 'unkjhiyrivblzlem'
DEFAULT_FROM_EMAIL = 'secureSab <securesabsena@gmail.com>'

# =====================================================
# FIN CONFIGURACIÓN DE CORREO
# =====================================================

# ==================== CONFIGURACIÓN POR DEFECTO ====================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== CONFIGURACIÓN DE CACHE ====================
CACHE_BACKEND = os.environ.get('DJANGO_CACHE_BACKEND', 'locmem').lower()

if CACHE_BACKEND == 'db':
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
            'LOCATION': os.environ.get('DJANGO_CACHE_TABLE', 'tabla_cache_huellas'),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'securesab-cache',
        }
    }