# Generated by Django 4.2.16 on 2026-06-22 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlamadoAtencion',
            fields=[
                ('id_llamado', models.AutoField(primary_key=True, serialize=False)),
                ('nivel', models.IntegerField(choices=[(1, 'Primer llamado de atención'), (2, 'Segundo llamado de atención'), (3, 'Tercer llamado - Proceso de deserción')])),
                ('total_inasistencias', models.IntegerField()),
                ('notificado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('id_instructor', models.ForeignKey(db_column='id_instructor', on_delete=django.db.models.deletion.CASCADE, related_name='llamados_emitidos', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='llamados_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Llamado de atención',
                'verbose_name_plural': 'Llamados de atención',
                'db_table': 'llamado_atencion',
            },
        ),
    ]
