# Generated by Django 4.2.16 on 2026-06-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_usuarios_id_ficha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roleuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
