# Generated by Django 4.2.16 on 2026-06-01 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coordinador', '0001_initial'),
    ]

    # Migration converted to a no-op because the database schema
    # already matches the desired column names (MariaDB). Executing
    # the original AlterField operations against the live DB caused
    # "Unknown column 'id_usuario_id'" errors. To avoid destructive
    # or incompatible schema operations, leave this migration as a
    # no-op and mark it applied.
    operations = []
