# Generated by Django 4.2.16 on 2026-06-01 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_alter_asistenciaambiente_id_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciaambiente',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='asistenciasede',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='competencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='coordinacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ficha',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='fichainstructor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='jornada',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='justificacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='novedad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programacompetencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='resultadoaprendizaje',
            options={'managed': False},
        ),
    ]
