# Generated by Django 5.0.6 on 2026-03-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaSede',
            fields=[
                ('id_asistencia_sede', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_instructor', models.IntegerField(blank=True, null=True)),
                ('id_competencia', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(max_length=20)),
            ],
        ),
    ]
