# Generated by Django 5.0.6 on 2026-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huella',
            fields=[
                ('id_huella', models.AutoField(primary_key=True, serialize=False)),
                ('datos_huella_dactilar', models.BinaryField()),
                ('fecha_registro', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'huella',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
