# Generated by Django 5.0.6 on 2026-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0002_huella_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia_ambiente',
            fields=[
                ('id_asistencia_ambiente', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_instructor', models.IntegerField(blank=True, null=True)),
                ('ficha', models.CharField(max_length=20)),
                ('coordinacion', models.CharField(max_length=100)),
                ('programa', models.CharField(max_length=100)),
                ('id_competencia', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='registro_actividad',
            fields=[
                ('id_registro_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('actividad', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
