# Generated by Django 5.0.6 on 2026-04-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0003_asistencia_ambiente_registro_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencia_sede',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado_asistencia', models.CharField(max_length=255)),
                ('id_instructor', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asistencia_sede',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AsistenciaSede',
        ),
    ]
