# Generated by Django 5.0.6 on 2026-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0005_asistenciaambiente_asistenciasede_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('guard_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
    ]
