# Generated by Django 5.0.6 on 2026-04-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0006_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('role_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'role_user',
                'managed': False,
            },
        ),
    ]
