# Generated by Django 5.0.6 on 2026-04-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0007_roleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id_ficha', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ficha', models.CharField(max_length=50)),
                ('fecha', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('id_programa', models.IntegerField()),
                ('id_jornada', models.IntegerField()),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
    ]
