# Generated by Django 4.2.16 on 2026-06-01 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestor_sistema', '0008_ficha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_actividad',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AddField(
            model_name='registro_actividad',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro_actividad',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro_actividad',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registro_actividad',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='registro_actividad',
            table='registro_actividad',
        ),
        migrations.CreateModel(
            name='HistorialFallos',
            fields=[
                ('id_fallo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_fallo', models.CharField(choices=[('HUELLA_FALLIDA', 'Huella no coincide'), ('SIN_HUELLA', 'Usuario sin huella registrada'), ('LECTOR_ERROR', 'Error en el lector biométrico'), ('TIMEOUT', 'Tiempo excedido'), ('USUARIO_NO_EXISTE', 'Usuario no registrado en el sistema')], max_length=50)),
                ('cedula_intentada', models.CharField(blank=True, max_length=191, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_fallos',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
