# Generated by Django 4.2.16 on 2026-06-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_sistema', '0009_alter_registro_actividad_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialfallos',
            options={'managed': False, 'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='registro_actividad',
            options={'managed': False, 'ordering': ['-fecha', '-hora']},
        ),
    ]
